## Connect to Wharton Research Data Services (WRDS)

In [14]:
import wrds
import os
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

True

In [ ]:
db = wrds.Connection(wrds_username=os.getenv("WRDS_USERNAME"))

In [ ]:
libraries = db.list_libraries()

In [ ]:
crsp = db.list_tables(library='crsp')

In [ ]:
dsf_info = db.describe_table(library="crsp", table="dsf")
dsf_info

Approximately 107682104 rows in crsp.dsf.

,name,nullable,type,comment
0,cusip,True,VARCHAR(8),CUSIP Header
1,permno,True,INTEGER,PERMNO
2,permco,True,INTEGER,PERMCO
3,issuno,True,INTEGER,Nasdaq Issue Number
4,hexcd,True,SMALLINT,Exchange Code Header
5,hsiccd,True,INTEGER,Standard Industrial Classification Code Header
6,date,True,DATE,Date of Observation
7,bidlo,True,"NUMERIC(11, 5)",Bid or Low Price
8,askhi,True,"NUMERIC(11, 5)",Ask or High Price
9,prc,True,"NUMERIC(11, 5)",Price or Bid/Ask Average
10,vol,True,"NUMERIC(10, 0)",Volume
11,ret,True,"NUMERIC(10, 6)",Returns
12,bid,True,"NUMERIC(11, 5)",Bid
13,ask,True,"NUMERIC(11, 5)",Ask
14,shrout,True,DOUBLE PRECISION,Shares Outstanding
15,cfacpr,True,DOUBLE PRECISION,Cumulative Factor to Adjust Prices
16,cfacshr,True,DOUBLE PRECISION,Cumulative Factor to Adjust Shares/Vol
17,openprc,True,"NUMERIC(11, 5)",Open Price
18,numtrd,True,INTEGER,NASDAQ Number of Trades
19,retx,True,"NUMERIC(10, 6)",Returns without Dividends

In [ ]:
dsfv2_info = db.describe_table(library="crsp", table="dsf_v2")
dsfv2_info

Approximately 110257376 rows in crsp.dsf_v2.

,name,nullable,type,comment
0,permno,True,INTEGER,PERMNO
1,hdrcusip,True,VARCHAR(8),Header CUSIP -8 Characters
2,permco,True,INTEGER,PERMCO
3,siccd,True,INTEGER,Sic Code
4,nasdissuno,True,INTEGER,Nasdaq Issue Number
5,yyyymmdd,True,INTEGER,YYYYMMDD - Daily Calendar Period Key
6,sharetype,True,VARCHAR(3),Share Type
7,securitytype,True,VARCHAR(4),Security Type
8,securitysubtype,True,VARCHAR(3),Security Sub-Type
9,usincflg,True,VARCHAR(1),US Incorporation Flag
10,issuertype,True,VARCHAR(4),Issuer Type
11,primaryexch,True,VARCHAR(1),Primary Exchange
12,conditionaltype,True,VARCHAR(3),Conditional Type
13,tradingstatusflg,True,VARCHAR(1),Trading Status Flag
14,dlycaldt,True,DATE,Daily Calendar Date
15,dlydelflg,True,VARCHAR(1),Daily Delisting Flag
16,dlyprc,True,"NUMERIC(13, 6)",Daily Price
17,dlyprcflg,True,VARCHAR(2),Daily Price Flag
18,dlycap,True,"NUMERIC(13, 2)",Daily Capitalization
19,dlycapflg,True,VARCHAR(2),Daily Capitalization Flag
20,dlyprevprc,True,"NUMERIC(13, 6)",Daily Previous Price
21,dlyprevprcflg,True,VARCHAR(2),Daily Previous Price Flag
22,dlyprevdt,True,DATE,Daily Previous Price Date
23,dlyprevcap,True,"NUMERIC(13, 2)",Daily Previous Capitalization
24,dlyprevcapflg,True,VARCHAR(2),Daily Previous Capitalization Flag
25,dlyret,True,"NUMERIC(10, 6)",Daily Total Return
26,dlyretx,True,"NUMERIC(10, 6)",Daily Price Return
27,dlyreti,True,"NUMERIC(10, 6)",Daily Income Return
28,dlyretmissflg,True,VARCHAR(2),Daily Return Missing Flag
29,dlyretdurflg,True,VARCHAR(2),Daily Return Duration Flag
30,dlyorddivamt,True,"NUMERIC(13, 6)",Daily Ordinary Dividend Amount
31,dlynonorddivamt,True,"NUMERIC(13, 6)",Daily Non-Ordinary Dividend Amount
32,dlyfacprc,True,"NUMERIC(10, 6)",Daily Factor To Adjust Price
33,dlydistretflg,True,VARCHAR(2),Daily Distribution Return Impact Flag
34,dlyvol,True,"NUMERIC(14, 0)",Daily Volume
35,dlyclose,True,"NUMERIC(13, 6)",Daily Close
36,dlylow,True,"NUMERIC(13, 6)",Daily Low
37,dlyhigh,True,"NUMERIC(13, 6)",Daily High
38,dlybid,True,"NUMERIC(13, 6)",Daily Bid
39,dlyask,True,"NUMERIC(13, 6)",Daily Ask
40,dlyopen,True,"NUMERIC(13, 6)",Daily Open
41,dlynumtrd,True,INTEGER,Daily Number Of Trades
42,dlymmcnt,True,SMALLINT,Daily Market Maker Count
43,dlyprcvol,True,"NUMERIC(14, 1)",Daily Price Volume
44,dlycumfacpr,True,"NUMERIC(17, 12)",Daily Cumulative Factor to Adjust Price
45,dlycumfacshr,True,"NUMERIC(17, 12)",Daily Cumulative Factor to Adjust Shares
46,cusip,True,VARCHAR(8),CUSIP
47,ticker,True,VARCHAR(5),Ticker
48,exchangetier,True,VARCHAR(3),Exchange Tier
49,shrout,True,INTEGER,Shares Outstanding

### Get S&P500 Constituents

* Get all S&P constituents since 1957-03-04, when S&P 500 is officially created.
* Get their daily price in the time being.

(Note on SQL: inner join daily price of each stock in the given S&P500 perio, left join their common name / ticker)

In [ ]:
sp500 = db.raw_sql("""
    SELECT
        a.*,
        b.comnam,
        b.namedt,
        b.nameendt,
        b.ticker,
        c.dlycaldt AS date,
        c.dlyprc

    FROM crsp.msp500list AS a

    INNER JOIN crsp.dsf_v2 AS c
        ON a.permno = c.permno
        AND c.dlycaldt BETWEEN a.start AND a.ending
       

    LEFT JOIN crsp.msenames AS b
        ON a.permno = b.permno
        AND c.dlycaldt BETWEEN b.namedt AND b.nameendt

    WHERE c.dlycaldt >= DATE '1957-03-04'
    
    ORDER BY c.dlycaldt, a.permno
""",
date_cols=[
    "start",
    "ending",
    "namedt",
    "nameendt",
    "date"
])

sp500

,permno,start,ending,comnam,namedt,nameendt,ticker,date,dlyprc
0,10006,1957-03-01,1984-07-18,A C F INDUSTRIES INC,1954-06-01,1962-07-01,<NA>,1957-03-04,60.75
1,10030,1957-03-01,1969-01-08,AMERICAN BRAKE SHOE CO,1943-04-27,1962-07-01,<NA>,1957-03-04,43.125
2,10057,1957-03-01,1992-07-02,NATIONAL ACME CO,1925-12-31,1962-07-01,<NA>,1957-03-04,73.0
3,10102,1957-03-01,1975-02-05,AIR REDUCTION INC,1925-12-31,1962-07-01,<NA>,1957-03-04,52.5
4,10137,1925-12-31,1976-06-30,WEST PENN ELECTRIC CO,1948-01-16,1960-11-09,<NA>,1957-03-04,26.25
...,...,...,...,...,...,...,...,...,...
44786,93096,2012-12-03,2024-12-31,DOLLAR GENERAL CORP NEW,2024-03-12,2024-12-31,DG,2024-12-31,75.82
44787,93132,2018-10-11,2024-12-31,FORTINET INC,2019-08-02,2024-12-31,FTNT,2024-12-31,94.48
44788,93246,2021-03-22,2024-12-31,GENERAC HOLDINGS INC,2010-02-11,2024-12-31,GNRC,2024-12-31,155.05
44789,93429,2017-03-01,2024-12-31,C B O E GLOBAL MARKETS INC,2024-06-21,2024-12-31,CBOE,2024-12-31,195.4
44790,93436,2020-12-21,2024-12-31,TESLA INC,2024-06-20,2024-12-31,TSLA,2024-12-31,403.84